heat_template_version: 2017-02-24

description: LoadBalancer creation.


###################################################################################
############################ Seccion de Parametros ################################
###################################################################################

parameters:

  subnet:
    type: string
    label: Subnet ID
    description: ID of the Sub-Network in which the admin server will be connected to.


###################################################################################
###################################################################################
###################################################################################



###################################################################################
############################# Seccion de Recursos #################################
###################################################################################

resources:

  loadbalancer:
    type: OS::Neutron::LBaaS::LoadBalancer
    properties:
      name: loadbalancer
      vip_subnet: { get_param: subnet }

  lb_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: ExtNet
      port_id: { get_attr: [loadbalancer, vip_port_id ]}

  listener:
    type: OS::Neutron::LBaaS::Listener
    properties:
      loadbalancer: { get_resource: loadbalancer }
      protocol: HTTP
      protocol_port: 80

  pool:
    type: OS::Neutron::LBaaS::Pool
    properties:
      lb_algorithm: ROUND_ROBIN
      protocol: HTTP
      listener: { get_resource: listener }


###################################################################################
###################################################################################
###################################################################################



###################################################################################
############################# Seccion de Salidas ##################################
###################################################################################

outputs:
  Pool_output:
    description: The Pool resource that has been created.
    value: { get_resource: pool }


###################################################################################
###################################################################################
###################################################################################