heat_template_version: 2017-02-24

description: Pool member creation.


###################################################################################
############################ Seccion de Parametros ################################
###################################################################################

parameters:

  subnet:
    type: string
    label: Subnet ID
    description: ID of the Sub-Network in which the admin server will be connected to.

  pool:
    type: string
    label: Pool
    description: Pool of load balancer from which pool members will connect.

  server_ip:
    type: string
    label: Server IP Address
    description: IP Address of server that will form a pool member of load balancer.


###################################################################################
###################################################################################
###################################################################################



###################################################################################
############################# Seccion de Recursos #################################
###################################################################################

resources:

  pool_member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_param: pool }
      address: { get_param: server_ip }
      protocol_port: 8080
      subnet: { get_param: subnet }

###################################################################################
###################################################################################
###################################################################################



###################################################################################
############################# Seccion de Salidas ##################################
###################################################################################

outputs:
  Pool_output:
    description: The Pool Member resource that has been created.
    value: { get_resource: pool_member }


###################################################################################
###################################################################################
###################################################################################