heat_template_version: 2017-02-24

description: Router creation.


###################################################################################
############################ Seccion de Parametros ################################
###################################################################################

parameters:

  router_name:
    type: string
    label: Router Name
    description: Name of the router of the scenario.


###################################################################################
###################################################################################
###################################################################################



###################################################################################
############################# Seccion de Recursos #################################
###################################################################################

resources:

  router:
    type: OS::Neutron::Router
    properties:
      name: { get_param: router_name }
      external_gateway_info:
        network: ExtNet 


###################################################################################
###################################################################################
###################################################################################



###################################################################################
############################# Seccion de Salidas ##################################
###################################################################################

outputs:

  RouterResource:
    description: The Router resource that has been created.
    value: { get_resource: router }


###################################################################################
###################################################################################
###################################################################################